spring:
  data:
    mongodb:
      uri: mongodb+srv://pablrohe:GHUBF699IIA7cYos@cluster0.el8qce5.mongodb.net/TwitterDataBase?retryWrites=true&w=majority
      auto-index-creation: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  docker:
    compose:
      lifecycle-management: none
springdoc:
  pathsToMatch: /api/**
